"""Add execution_state to events

Revision ID: bb07211120c7
Revises: 0009_phase13
Create Date: 2026-09-26 01:54:17.767125

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb07211120c7'
down_revision: Union[str, None] = '0009_phase13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_pause_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('operation_type', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('previous_state', sa.String(length=50), nullable=False),
    sa.Column('target_state', sa.String(length=50), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approval_reference', sa.String(length=36), nullable=True),
    sa.Column('validation_result', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('audit_reference', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_pause_records_created_at'), 'event_pause_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_pause_records_event_id'), 'event_pause_records', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_pause_records_operation_type'), 'event_pause_records', ['operation_type'], unique=False)
    op.create_index(op.f('ix_event_pause_records_requested_by'), 'event_pause_records', ['requested_by'], unique=False)
    op.create_index(op.f('ix_event_pause_records_status'), 'event_pause_records', ['status'], unique=False)
    op.create_table('vendor_outcomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('communication_channel', sa.String(length=50), nullable=False),
    sa.Column('outcome_status', sa.String(length=50), nullable=False),
    sa.Column('quoted_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('reported_availability', sa.String(length=50), nullable=False),
    sa.Column('organizer_notes', sa.Text(), nullable=True),
    sa.Column('vendor_response', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('submitted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_outcomes_event_id'), 'vendor_outcomes', ['event_id'], unique=False)
    op.create_index(op.f('ix_vendor_outcomes_outcome_status'), 'vendor_outcomes', ['outcome_status'], unique=False)
    op.create_index(op.f('ix_vendor_outcomes_provider_id'), 'vendor_outcomes', ['provider_id'], unique=False)
    op.create_index(op.f('ix_vendor_outcomes_task_id'), 'vendor_outcomes', ['task_id'], unique=False)
    op.create_table('vendor_outcome_validations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vendor_outcome_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('overall_status', sa.String(length=50), nullable=False),
    sa.Column('extracted_claims', sa.JSON(), nullable=False),
    sa.Column('claim_results', sa.JSON(), nullable=False),
    sa.Column('hard_requirements_passed', sa.JSON(), nullable=False),
    sa.Column('hard_requirements_failed', sa.JSON(), nullable=False),
    sa.Column('preferences_matched', sa.JSON(), nullable=False),
    sa.Column('conflicts', sa.JSON(), nullable=False),
    sa.Column('unknown_facts', sa.JSON(), nullable=False),
    sa.Column('validator_version', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_outcome_id'], ['vendor_outcomes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_outcome_validations_event_id'), 'vendor_outcome_validations', ['event_id'], unique=False)
    op.create_index(op.f('ix_vendor_outcome_validations_overall_status'), 'vendor_outcome_validations', ['overall_status'], unique=False)
    op.create_index(op.f('ix_vendor_outcome_validations_provider_id'), 'vendor_outcome_validations', ['provider_id'], unique=False)
    op.create_index(op.f('ix_vendor_outcome_validations_task_id'), 'vendor_outcome_validations', ['task_id'], unique=False)
    op.create_index(op.f('ix_vendor_outcome_validations_vendor_outcome_id'), 'vendor_outcome_validations', ['vendor_outcome_id'], unique=False)
    with op.batch_alter_table('action_executions') as batch_op:
        try:
            batch_op.drop_constraint(op.f('uq_action_executions_action_id'), type_='unique')
        except Exception:
            pass
        try:
            batch_op.drop_index(op.f('ix_action_executions_action_id'))
        except Exception:
            pass
        batch_op.create_index(op.f('ix_action_executions_action_id'), ['action_id'], unique=True)

    with op.batch_alter_table('events') as batch_op:
        batch_op.add_column(sa.Column('execution_state', sa.String(length=50), server_default='RUNNING', nullable=False))
        batch_op.create_index(op.f('ix_events_execution_state'), ['execution_state'], unique=False)

    with op.batch_alter_table('permissions') as batch_op:
        try:
            batch_op.drop_constraint(op.f('uq_permissions_name'), type_='unique')
        except Exception:
            pass

    with op.batch_alter_table('roles') as batch_op:
        try:
            batch_op.drop_constraint(op.f('uq_roles_name'), type_='unique')
        except Exception:
            pass

    with op.batch_alter_table('tasks') as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.String(length=36), nullable=True))
        batch_op.create_index(op.f('ix_tasks_provider_id'), ['provider_id'], unique=False)

    with op.batch_alter_table('users') as batch_op:
        try:
            batch_op.drop_constraint(op.f('uq_users_email'), type_='unique')
        except Exception:
            pass

    try:
        op.create_index(op.f('ix_vendor_assignments_approval_id'), 'vendor_assignments', ['approval_id'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_vendor_assignments_negotiation_status'), 'vendor_assignments', ['negotiation_status'], unique=False)
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_index(op.f('ix_vendor_assignments_negotiation_status'), table_name='vendor_assignments')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_vendor_assignments_approval_id'), table_name='vendor_assignments')
    except Exception:
        pass
    try:
        op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    except Exception:
        pass
    with op.batch_alter_table('tasks') as batch_op:
        try:
            batch_op.drop_index(op.f('ix_tasks_provider_id'))
        except Exception:
            pass
        try:
            batch_op.drop_column('provider_id')
        except Exception:
            pass
    try:
        op.drop_constraint(op.f('uq_roles_name'), 'roles', type_='unique')
    except Exception:
        pass
    try:
        op.drop_constraint(op.f('uq_permissions_name'), 'permissions', type_='unique')
    except Exception:
        pass
    with op.batch_alter_table('events') as batch_op:
        try:
            batch_op.drop_index(op.f('ix_events_execution_state'))
        except Exception:
            pass
        try:
            batch_op.drop_column('execution_state')
        except Exception:
            pass
    with op.batch_alter_table('action_executions') as batch_op:
        try:
            batch_op.drop_index(op.f('ix_action_executions_action_id'))
        except Exception:
            pass
        try:
            batch_op.create_index(op.f('ix_action_executions_action_id'), ['action_id'], unique=False)
        except Exception:
            pass
    try:
        op.create_unique_constraint(op.f('uq_action_executions_action_id'), 'action_executions', ['action_id'], postgresql_nulls_not_distinct=False)
    except Exception:
        pass
    op.drop_index(op.f('ix_vendor_outcome_validations_vendor_outcome_id'), table_name='vendor_outcome_validations')
    op.drop_index(op.f('ix_vendor_outcome_validations_task_id'), table_name='vendor_outcome_validations')
    op.drop_index(op.f('ix_vendor_outcome_validations_provider_id'), table_name='vendor_outcome_validations')
    op.drop_index(op.f('ix_vendor_outcome_validations_overall_status'), table_name='vendor_outcome_validations')
    op.drop_index(op.f('ix_vendor_outcome_validations_event_id'), table_name='vendor_outcome_validations')
    op.drop_table('vendor_outcome_validations')
    op.drop_index(op.f('ix_vendor_outcomes_task_id'), table_name='vendor_outcomes')
    op.drop_index(op.f('ix_vendor_outcomes_provider_id'), table_name='vendor_outcomes')
    op.drop_index(op.f('ix_vendor_outcomes_outcome_status'), table_name='vendor_outcomes')
    op.drop_index(op.f('ix_vendor_outcomes_event_id'), table_name='vendor_outcomes')
    op.drop_table('vendor_outcomes')
    op.drop_index(op.f('ix_event_pause_records_status'), table_name='event_pause_records')
    op.drop_index(op.f('ix_event_pause_records_requested_by'), table_name='event_pause_records')
    op.drop_index(op.f('ix_event_pause_records_operation_type'), table_name='event_pause_records')
    op.drop_index(op.f('ix_event_pause_records_event_id'), table_name='event_pause_records')
    op.drop_index(op.f('ix_event_pause_records_created_at'), table_name='event_pause_records')
    op.drop_table('event_pause_records')
    # ### end Alembic commands ###
